agora2/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('frontend.urls', namespace='frontend')),
]

frontend/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import add_to_cart_view, get_products, get_cart_data


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='frontend/catalog.html'), name='main'),
    url(r'^catalog/$', TemplateView.as_view(template_name='frontend/catalog.html'), name='catalog_page'),
    url(r'^catalog/products-ajax/$', get_products, name='get_products_ajax'),
    url(r'^carts/add-to-cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^carts/get-cart-data-ajax/$', get_cart_data, name='get_cart_data'),
    url(r'^carts/cart/$', TemplateView.as_view(template_name='frontend/cart.html'), name='cart_page'),
]

carts/models.py
from django.db import models


class Cart(models.Model):
    user_id = models.IntegerField(unique=True)


class CartItem(models.Model):
    cart_id = models.IntegerField()
    product_id = models.IntegerField()
    quantity = models.PositiveSmallIntegerField(default=0, blank=True)
    price = models.FloatField(blank=True, null=True)

    class Meta:
        unique_together = ['cart_id', 'product_id']

frontend/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .adapters.carts import add_to_cart, get_cart
from .adapters.products import get_all_products


@csrf_exempt
def add_to_cart_view(request):
    product_id = int(request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))
    add_to_cart(
        user_id=1,
        product_id=product_id,
        quantity=quantity,
    )
    return HttpResponse('ok')


def get_products(request):
    # products = [
    #     {
    #         'id': 1,
    #         'name': 'Product 1',
    #     },
    #     {
    #         'id': 2,
    #         'name': 'Product 2',
    #     },
    #     {
    #         'id': 3,
    #         'name': 'Product 3',
    #     },
    # ]
    products = get_all_products()
    return JsonResponse({
        'objects': products,
    })


def get_cart_data(request):
    user_id = 1
    cart_DTO = get_cart(user_id)
    return JsonResponse(cart_DTO, safe=False)

sales/carts/views.py
from .api.v_1_0.commands import AddToCart

def add_to_cart(request):
    product_modification_id = request.POST.get('product_modification_id', None)
    service = AddToCart()
    service.run()

frontend/templates/frontend/cart.html
{% extends "frontend/layout.html" %}
{% load static %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="cart">
        <div id="cart-items">
            <ul>
                <cartitem
                        v-for="item in items"
                        v-bind:item="item"
                        v-bind:key="item.id"
                >
                    <template id="tpl-cart-item">
                        <li class="cart-item">
                            ${ item.product_name }
                             (<a href="#" class="proditem__link" @click="remove_from_cart(item.id)">remove</a>)
                        </li>
                    </template>
                </cartitem>
            </ul>
        </div>
    </div>
{% endblock content %}

{% block js_bottom %}
    {{ block.super }}

    <script>
        Vue.component('cartitem', {
            delimiters: ['${', '}'],
            props: ['item'],
            template: '#tpl-cart-item',
            methods: {
                remove_from_cart: function(item_id) {
                    var data = {
                        item_id: item_id,
                    };
                    $.post('/carts/remove-from-cart/', data).success(function(d){
                        alert('ok');
                    })
                }
            }
        });
        $.get('/carts/get-cart-data-ajax/', function(data){
            console.log(data.items);
            var cart_items = new Vue({
                delimiters: ['${', '}'],
                el: '#cart-items',
                data: {
                    items: data.items,
                }
            });
        });
    </script>
{% endblock %}

frontend/templates/frontend/catalog.html
{% extends "frontend/layout.html" %}
{% load static %}

{% block title %}
    Catalog
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="prodcatalog">
        <div class="prodcatalog__filters"></div>

        <div id="products-list">
            <ul>
                <proditem
                        v-for="product in products"
                        v-bind:product="product"
                        v-bind:key="product.id"
                >
                    <template id="tpl-proditem">
                        <li class="proditem">
                            <strong>${ product.name }</strong>
                            <div>
                                <label>Price:</label>
                                <span>${ product.main_price.value }</span>
                            </div>
                            <a href="#" class="proditem__link" @click="add_to_cart(product.id)">Add to cart</a>
                        </li>
                    </template>
                </proditem>
            </ul>
        </div>
    </div>
{% endblock content %}

{% block js_bottom %}
    {{ block.super }}

    <script>
        Vue.component('proditem', {
            delimiters: ['${', '}'],
            props: ['product'],
            template: '#tpl-proditem',
            methods: {
                add_to_cart: function(product_id) {
                    var data = {
                        product_id: product_id,
                        quantity: 1,
                    };
                    $.post('/carts/add-to-cart/', data, function(d){
                        alert('ok');
                    })
                }
            }
        });
        $.get('/catalog/products-ajax/', function(data){
            var product_list = new Vue({
                delimiters: ['${', '}'],
                el: '#products-list',
                data: {
                    products: data['objects'],
                }
            });
            setInterval(function(){

            });
        });
    </script>
{% endblock %}

frontend/templates/frontend/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Agora 2</title>
    {% block css %}{% endblock css %}
</head>
<body>
    <div class="main-nav">
        <span class="nav-item">
            <a href="{% url "frontend:catalog_page" %}">Каталог</a>
            <a href="{% url "frontend:cart_page" %}">Козина</a>
        </span>
    </div>

    <h1>{% block title %}{% endblock title %}</h1>
    {% block content %}{% endblock content %}
    {% block js_bottom %}
        <script src="{% static "third-party/jquery-3.2.1.min.js" %}"></script>
        <script src="{% static "third-party/vue/vue.min.js" %}"></script>
    {% endblock js_bottom %}
</body>
</html>